### ISSUE TITLE
Won't save selected sound as WAV file

### ISSUE THREAD

**Issue by KerryPreSLP** [praat/praat#1290]
I am a student and I have been using Praat all semester on my HP Windows Laptop. I have a big project I am working on and I need to be able to save a new WAV file from an existing one by selecting a particular word in the file. I have done this in the past with no issue. Suddenly it will not save. Praat still has the option from the drop-down menu to "save selected sound as WAV file". Once I click it and the save window pops up, it allows me to type a file name for it, but the file type drop-down is blank and does not have any options for me to select. If I save it anyways it saves as a "file" type file. It will still play if I open it through Windows media player, but I cannot insert it to my Microsoft PowerPoint presentation because it is not a WAV file. 
Can anyone help me ASAP Please?
Thank you!
-Kerry

**Comment by PaulBoersma** [comment]
You must have changed the "show all extensions" setting on your laptop. Anyway, you can still save the file by typing the name as "hello.wav" or so. If don't type the ".wav" extension, the file will just be called "hello"; it will still be a WAV file, and Praat will recognize it as a WAV file, but Windows Media Player will not recognize it, because Windows Media Player recognizes the file type by the extension instead of from the content. As for the file you already saved, just give it the ".wav" extension and PowerPoint will be happy with it.
