### ISSUE TITLE
filename duplicated when PointProcess (cc) selected.

### ISSUE THREAD

**Issue by leochoo** [praat/praat#1340]
![Screen Shot 2020-06-17 at 18 19 27](https://user-images.githubusercontent.com/26427048/84880512-90a60000-b0c7-11ea-9d04-7776eda35b19.png)

I ran the script below to automatically generate the voice report.
http://phonetics.linguistics.ucla.edu/facilities/acoustic/voice_rep_from_object_window.txt

However, it was keep having trouble at line 112.
I realized that it was because the PointProcess file generated in PRAAT had name of PointProcess object duplicated as shown on the screenshot `151-i_n_151-i_n`, whereas the program was looking for the correct title `151-i_n`

**Comment by PaulBoersma** [comment]
When you select a Sound called "A" and a Pitch called "B", and then choose "To PointProcess", the name of the resulting PointProcess object will be "A_B". That's all. The name "A_B" is intended, although apparently not what you expected.
   It is advisable to work with object IDs instead of object names in your script.
