### ISSUE TITLE
Views blank on macOS 11 Beta (Big Sur)

### ISSUE THREAD

**Issue by tedgoddard** [praat/praat#1364]
When the released version of Praat is run on macOS 11 Beta (Big Sur) most of the views are empty, only buttons are visible and are not functional.

**Comment by tedgoddard** [comment]
Also building from source on macOS 10.14.6 compiles and runs but the spectrogram is not visible.

**Comment by tedgoddard** [comment]
@PaulBoersma I'm happy to help debug this, but need some guidance on where to start.

**Comment by PaulBoersma** [comment]
Building from the latest "unstable" source should yield a more-or-less running Praat on Big Sur. I will publish an alpha version around August 10.

**Comment by PaulBoersma** [comment]
This is not about debugging, but about rewriting thousands of lines of code. All dragging operations, for instance, have to be converted from event-pull-based to event-push-based, so to say, and drawing can only be performed at expose event time.

**Comment by tedgoddard** [comment]
Thanks for the advice to build from master, it's now running well for us on Big Sur (except for the time tracking line in the spectrogram).

You can always count on Apple for lots of breaking API changes that really don't change much in real terms.

**Comment by PaulBoersma** [comment]
If you really like to help debugging: many things in Praat do not work correctly yet. For instance, `demoShow` does not always work, as shown by `test/manually/Demo_recording_problem.praat`. The problem seems to reside in the fact that Apple's `display` method (used in `GuiShell_drain`), which should force and send an expose event, does not always seem to do so, especially if it is called twice in a row with little time in between. Note that `flushWindow` and `lockFocus` have been deprecated, so their use is not likely to help.

**Comment by PaulBoersma** [comment]
Present versions of Praat run fine on BigSur.
