### ISSUE TITLE
How to generate an spectrogram without margin/padding

### ISSUE THREAD

**Issue by LeonardoDelgado1905** [praat/praat#1584]
We are trying to create a script to export spectrogram images without margin/padding to generate data for a deep learning model 

### Original Image
![spectogram](https://github.com/nestorsgarzonc/LISI_VocalesCNN/blob/master/Datos/praat.png?raw=true)

As you can see, this image have a margin at all directions, and we want to know how to remove or what is the margin in pixels to remove, we tried to do that but it was not perfect

### Modified Image
![spectogram2](https://github.com/nestorsgarzonc/LISI_VocalesCNN/blob/master/Datos/comoqueremos.png?raw=true)

**Comment by PaulBoersma** [comment]
The spectrogram is painted for all times where it can be defined. In order to be able to define a vertical spectrum at time t, the waveform has to be defined between t - Dt/2 and t + Dt/2, where Dt is the duration of the analysis window. This is one of the most asked questions, and you can find it in the Intro in Praat's help.
