### ISSUE TITLE
Reading of ogg file stalls on i386

### ISSUE THREAD

**Issue by rlaboiss** [praat/praat#1734]
The latest version of Praat (4.1.42) for Debian is not building correctly on the i386 architecture. The package compilation run into a hanging state when exercising the unit test test_readAudioFiles.praat ([full log](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=i386&ver=6.1.42-1&stamp=1620186275&file=log)).

It seems that the script gets stuck at the command `vorbis  = Read from file: "Example_vorbis_audio.ogg"` (it does succeed to read the Opus file, though).

Any suggestion on how to debug this problem?

**Comment by PaulBoersma** [comment]
This must occur in dwtools/Sound_readFromOggVorbisFile.cpp. I do see "while (true)" in that code, and the only break from the loop occurs when ogg_stream_packetout returns 0. Is it possible for ogg_stream_packetout to always return something unequal to 0? That would explain a hang. There are also two instances of "while (! eos)", and these could hang if ogg_page_eos keeps on returning 0. These facts suggest where one could look for the results of these OGG functions, to see which of the two refuses to yield 0 (for ogg_stream_packetout) or not 0 (for ogg_page_eos).

**Comment by rlaboiss** [comment]
I think that I will disable the running of the unit test test_readAudioFiles.praat in the Debian package building for now. I do not have time for debugging this problem on i386. Moreover, the i386 architecture [will eventually be dropped from Debian](https://www.phoronix.com/scan.php?page=news_item&px=Debian-11-Freeze-Starts) at some point…

**Comment by PaulBoersma** [comment]
I tried to start debugging Praat for i386 Linux today, but it turned out that my 32-bit Ubuntu Mate could no longer start up with the current version of Parallels Desktop. Consider that dropped.

On my 32-bit Raspberry PI, the script gives an interesting error, namely "Error: Input does not appear to be an Ogg Vorbis bitstream."  This can well be due to the same bug that caused a crash on your i386, so I will be able to investigate now.

**Comment by rlaboiss** [comment]
Great, I hope you will be able to find the origin of the bug.

**Comment by PaulBoersma** [comment]
Yes, found. It is interesting. The bug was in Xiph.org's Vorbis code:

    static ov_callbacks OV_CALLBACKS_NOCLOSE = {
        (size_t (*)(void *, size_t, size_t, void *))  fread,
        (int (*)(void *, ogg_int64_t, int))           fseek,
        (int (*)(void *))                             nullptr,
        (long (*)(void *))                            ftell
    };

They were casting the function `fseek`, which on 32-bit platforms usually takes a 32-bit second parameter (the file position to jump to) to a function that takes a 64-bit second parameter. Yes, that's undefined behaviour. The trick that Xiph.org performs here, achieves the opposite of what it is intended to do.

Turning `fseek` into `fseeko` turns out to prevent the error that I mentioned on the Raspberry Pi. You may try whether that also solves your crash on i386 Linux.

**Comment by rlaboiss** [comment]
I am impressed that you could nail down this bug. This is an upstream issue and should be reported to the upstream authors of Vorbis. Are you planning to do it? (I know that you decided to keep a copy of the Vorbis sources in the Praat sources, so that you do not need to wait for upstream fixes to have them propagated to Praat.)

**Comment by rlaboiss** [comment]
I [released a new version](https://tracker.debian.org/news/1248207/accepted-praat-6151-3-source-into-unstable/) of the Debian package for Praat (6.1.51.-3), that [includes](https://salsa.debian.org/med-team/praat/-/commit/f1d3b213bb3b052283ed694c0c75af123d02de1c) the relevant part of your commit c80187cafb31d0bae7b1ce18b4a236dbe572de2. The package [built correctly on i368](https://buildd.debian.org/status/fetch.php?pkg=praat&arch=i386&ver=6.1.51-3&stamp=1629313781&raw=0) (the unit test test_readAudioFiles.praat succeeded).

I am hereby closing this issue.
