### ISSUE TITLE
Issue compiling for windows

### ISSUE THREAD

**Issue by ghedlund** [praat/praat#2114]
I'm attempting to compile Praat for windows x64 using the current version available on github.
Using mingw 7.0.0-2 on ubuntu 20.04.

Error:
```
x86_64-w64-mingw32-g++ -std=gnu++17 -municode -D_FILE_OFFSET_BITS=64 -O3 -Wshadow -I ../melder  -c -o melder_textencoding.o melder_textencoding.cpp
cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
melder_textencoding.cpp: In function ‘const wchar_t* Melder_peek32toW_fileSystem(conststring32)’:
melder_textencoding.cpp:578:19: error: ‘NormalizationC’ was not declared in this scope
  578 |  NormalizeString (NormalizationC, Melder_peek32toW (string), -1, buffer, 1 + kMelder_MAXPATH);
      |                   ^~~~~~~~~~~~~~
melder_textencoding.cpp:578:2: error: ‘NormalizeString’ was not declared in this scope
  578 |  NormalizeString (NormalizationC, Melder_peek32toW (string), -1, buffer, 1 + kMelder_MAXPATH);
      |  ^~~~~~~~~~~~~~~
```

Any help would be appreciated, maybe I'm missing a required package/header?  I could not find any other references to ```NormalizationC``` in the code.

**Comment by PaulBoersma** [comment]
The Makefile is only for x86_64-w64-mingw32-g++ under Cygwin. What happens if you use the implicit flags explicitly, e.g. `-m64 -mwin32 -march=x86_64 -mtune=generic`?

By the way, how can your compiler complain about ‘-std=gnu99’ if that option is not included in `x86_64-w64-mingw32-g++ -std=gnu++17 -municode -D_FILE_OFFSET_BITS=64 -O3 -Wshadow -I ../melder  -c -o melder_textencoding.o melder_textencoding.cpp`?

**Comment by ghedlund** [comment]
Updating my sources from the current master branch corrected this issue.  I have also repaired my makefiles.

Regards,
-Greg

**Comment by liziru** [comment]
> Updating my sources from the current master branch corrected this issue. I have also repaired my makefiles.
> 
> Regards, -Greg

I have the same problem when compiling this project. Any advice to repair makefiles?
