### ISSUE TITLE
Formula for converting PitchTier to Point Process

### ISSUE THREAD

**Issue by tshmak** [praat/praat#2275]
Hi, 

I am trying to understand the maths behind Praat. Would you be able to explain where the algorithm [here](https://github.com/praat/praat/blob/382c64e43c64bf73b93fcec32ebfd788b5970a8d/fon/PitchTier_to_PointProcess.cpp#L39) comes from? 

Many thanks! 

Tim

**Comment by PaulBoersma** [comment]
That's the algorithm to determine where the next time point should come when we convert a pitch tier to a series of time points. A naive algorithm would be: if the latest point is at time t, and the current pitch is f, then the next point should be at time t' = t+1/f. This is incorrect, because the pitch may have changed between these two times. The correct algorithm should be such that the area under the pitch curve between t and t' is exactly 1. This means that if the pitch changes linearly from f to f' (between t and t'), t' and its accompanying f' should be chosen in such a way that (t' - t) times 0.5\*(f+f') equals 1, where the last expression means the average pitch between t and t'. The area under the linear curve is a quadratic function of t' (the definite integral of the pitch curve from t to t'). hence those "slope" (the slope of the pitch curve) and "discriminant" (the discriminant of the solution of a quadratic equation).

Does that help, or do you want to see the derivation of the precise solution as well?

**Comment by tshmak** [comment]
Wow, thanks very much. I think I understand now. That's very helpful of you.
