### ISSUE TITLE
Praat 6.4.06 - Windows 10 - Table: sort rows - GUI issues

### ISSUE THREAD

**Issue by rolandomunoz** [praat/praat#2608]
In the GUI I cannot sort a table by two or more columns using the command `Table: sort rows`.  This happens only when the option *comma-separated* and *semicolon-separated* are activated. For example, if you want to sort the table of Peterson & Barney (1952) by "Type F2 F3" Praat will raise an error message saying that F2 does not exist.

![image](https://github.com/praat/praat/assets/18198623/12837610-aaaf-4606-b46f-3287e0d6b369)

I tested *whitespace-separated*, *pipe-separated* and *one per line* modes, and they seem to work fine. The only thing with *one per line* mode is that I cannot insert multiple lines in the text widget because when I press enter or shift+enter (Windows 10) to insert a new line, Praat thinks I want to press OK button. Thus, I had to copy and paste the wanted list from Notepad.

I did not tested *formula* mode because I do not know how it works.

**Comment by PaulBoersma** [comment]
Comma separation is designed to enable the use of spaces inside the texts. So the first space in " F2" is counted as part of the text, as you see indeed in the error message. The right way to type your column list in a comma-separated way is `Type,F2,F3`. So this is a feature, not a bug. I have, however, changed the error message to `Column " F2" does not exist (note: it starts with a space).` for version 6.4.19, because this is probably a common mistake (though there exist several other potential space-related mistakes).
