### ISSUE TITLE
Importing vowel marks from table to VowelEditor errors with 'File does not contain valid Table data.'

### ISSUE THREAD

**Issue by tuboke** [praat/praat#2657]
I was trying to visualize a vowel grid using VowelEditor and its 'Show vowel marks from Table file' option, so I went by the manual and made a simple .csv file with these contents:
```
Vowel,F1,F2
i,278,1608
u,323,725
ɨ,352,1314
e,421,1351
o,448,785
a,555,976
```
Importing that file through 'Show vowel marks...' gave an invalid data error, so I imported the file to Praat and exported it with .table extension. Doing this produced the same error so in the .table file I tried changing delimiters to semicolons, tabs or spaces. None have worked.
I'm not sure if there's a set syntax for .table files but I didn't see any reference in the help pages and I don't know C++ in any capacity so I cannot reference the source code to look for any hints.

If this error is an expected outcome, what should I do to plot my own set of vowels?

Praat version: 6.4.13
OS: Arch Linux, praat installed through pacman package manager

**Comment by rolandomunoz** [comment]
OS: Windows 10
Praat: praat6413_win-intel64

In my machine, I can open these files:

1. `Table` object files
2. comma-separated files
3. tab-separated files

I cannot open these files:

1. space-separated files
2. semicolons-seperated files

Here are my examples.

[tables.zip](https://github.com/user-attachments/files/15855549/tables.zip)

**Comment by davidweenink** [comment]
@tuboke First of all: the  .csv is not a Praat Table file it is not even a table at all,  it is just a special text file (that can be interpreted as a table)
To create the Praat Table from it:
start Praat:

Read Table from comma-separated file... <your.csv>
Save as binary file... <your.Table>

From within the VowelEditor:
Show vowel marks from Table file: <your.Table>

This should always work.

@rolandomunoz

Read Table from semicolon-separated file... vowels-semicolons.csv
just works

Read Table from space-spaarated file... vowels-spaces.csv
also just works

Greetings,

David

**Comment by PaulBoersma** [comment]
Praat recognizes text files as tables (e.g. when dropping on the Praat icon) only if it was saved as a "Table" file from Praat, or if it is tab-separated. To read any of the other types, you would need to open it with one of the above specialized commands from the Open menu. This is because it's hard to interpret for instance the following file as a table (whitespace-separated or comma-separated?):

    You may write me down in history
    With your bitter, twisted lies,
    You may tread me in the very dirt
    But still, like dust, I'll rise.

Praat cannot decide on that; it’s you as a user who has to decide. But tab-separation is clear. So when `Show vowel marks...` imports a table, it should be tab-separated (or saved as a Table file, either text or binary). We’ll add this to the manual for version 6.4.20.
