### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by luigino** [praat/praat#333]
I'm trying to get praat accepted into a linux distribution but the licensing terms are unclear.

main/GNU_General_Public_License.txt is version 2.0, but under external there are several files with a gpl 3.0+ header.

Since I couldn't find anywhere a notice about the former being gpl 2.0 "or any later version", there are distributability issues with it being linked to the latter.

So, could you please clarify the question?

**Comment by PaulBoersma** [comment]
The GPL license text is that of 2.0, but the license texts in most Praat source code files say "version 2.0 or later". There does not exist any document defining "GPL 2.0 or later". The statement just means that these Praat source code files can be used in projects distributed under GPL 2.0, or under GPL 3.0, or under GPL 4, and so on. As some external files used by Praat are distributed under "GPL 3.0 or later", the complete distribution of Praat is compatible only with GPL 3.0 or later, not with GPL 2.0. There should be no problem, however, because I don't think there are any source file that just say "GPL 2.0", without saying "or later".

**Comment by luigino** [comment]
Ok, I couldn't find any either.
I guess that settles it.
