### ISSUE TITLE
Praat is generating 0 byte waveform

### ISSUE THREAD

**Issue by shrestha2lt8** [praat/praat#356]
I am generating the waveform from praat script. It's working great but only for attached audio file https://drive.google.com/file/d/0B820TayaGz1PUjhxUTlIVzZRQmM/view?usp=sharing for which I have a problem.

Below script generates the multiple waveform images based on its duration since there is a problem creating a single waveform for the longer audio so we have chosen this option to create waveforms for longer audio. This script generally working great for many audio files but we have got the problem for the audio https://drive.google.com/file/d/0B820TayaGz1PUjhxUTlIVzZRQmM/view?usp=sharing. It's generating 0 byte waveform that means no contents on waveform image while we are expecting the file size > 1 KB.

To test this audio please download the audio file from the above link and change the values for variables outputFolder$ (output location for waveform) and audioFile$  (source path of the audio file). After changing the values then please run the script from the praat application.

We have confirmed that there is a problem while saving waveform images whose responsible code is in bold text in the below script.

Below is the script which I am using.

outputFolder$ = "C:\Temp\ffmpeg\experiments"
audioFile$ = "D:\audio.mp3"

window_start = 0
full_window=3600;
divide=15;

if audioFile$ <> ""
	Read from file... 'audioFile$'
	audioName$ = selected$ ("Sound")
endif
To TextGrid... phrases
select TextGrid 'audioName$'
file_length = Get total duration

if file_length<=41*60
	full_window=2460
	divide=30;
endif

if file_length<=21*60
	full_window=1260
	divide=20;
endif

if file_length<=11*60
	full_window=660
	divide=15;
endif
	
if file_length>41*60
	full_window=3600
	divide=60;
endif

draw_num = floor(file_length/full_window)

last_draw = file_length - draw_num*full_window

if file_length<full_window
	view_width = 4 * file_length/divide
else
	view_width = 4 * full_window/divide
endif
view_width=view_width

for b from 1 to draw_num
  select TextGrid 'audioName$'
  window_end = window_start + full_window 
  start_int = Get interval at time... 1 window_start
  end_int = Get interval at time... 1 window_end
  select Sound 'audioName$'
  Line width... 1
  Viewport... 0 view_width 0 2
  Colour... {110, 110, 10}
  Draw... window_start window_end 0 0 no curve

  select Sound 'audioName$'
  To Intensity... 80 0
  Down to IntensityTier

  select Sound 'audioName$'
  To Pitch (ac)... 0.0 80 15 no 0.03 0.3 0.2 0.9 0.14 300
  Down to PitchTier

  select Intensity 'audioName$'
  Viewport... 0 view_width 1.25 2.25

  Colour... lime
  Line width... 2

  select Pitch 'audioName$'
  Viewport... 0 view_width 1.25 2.25

  Colour... green

  Line width... 1
  Draw... window_start window_end 80 300 no
  Line width... 2
  Draw... window_start window_end 80 300 no

  save_width = view_width - 0.60
  Viewport... 0.60 save_width 0.40 2
  **Save as 300-dpi PNG file... 'outputFolder$'\waveform_'b'.png**
  Erase all
  window_start = window_start + full_window 
endfor

select TextGrid 'audioName$'
window_start = file_length - last_draw
window_end = file_length
start_int = Get interval at time... 1 window_start
end_int = Get interval at time... 1 window_end
view_width = 4 * (window_end-window_start)/divide
select Sound 'audioName$'
Line width... 1
Viewport... 0 view_width 0 2
Colour... {110, 110, 10}
Draw... window_start window_end 0 0 no curve

select Sound 'audioName$'
To Intensity... 80 0
Down to IntensityTier

select Sound 'audioName$'
To Pitch (ac)... 0.0 80 15 no 0.03 0.3 0.2 0.9 0.14 300
Down to PitchTier

select Intensity 'audioName$'
#Viewport... 0 view_width 1.25 2.75
Viewport... 0 view_width 1 2.75

Colour... lime
Line width... 2

select Pitch 'audioName$'
Viewport... 0 view_width 1.25 2.75
Colour... green

Line width... 1
Draw... window_start window_end 80 300 no
Line width... 2
Draw... window_start window_end 80 300 no

final_num = draw_num + 1
save_width = view_width - 0.60
Viewport... 0.60 save_width 0.40 2.75
**Save as 300-dpi PNG file... 'outputFolder$'\waveform.png**
Erase all
window_start = window_start + full_window

**Comment by drammock** [comment]
for questions about debugging your scripts, please post to [the praat users group](https://uk.groups.yahoo.com/neo/groups/praat-users/info).  If you think this is a bug in praat (and not a bug in your script or a problem with your chosen sound file) then please create a **much** shorter example script that only includes the lines necessary to reproduce the bug (see [here](https://stackoverflow.com/help/mcve) and [here](http://sscce.org/) for guidance on how to do this).  Finally, if you post code samples in github issues, please put a row of three backticks `\`\`\`` above and below the script, so that GitHub does not mistakenly treat your `#` marks as [markdown](https://help.github.com/articles/about-writing-and-formatting-on-github/) formatting indicators.

**Comment by shrestha2lt8** [comment]
I have re-written the description. Hope now it has a clear description but sorry I could not make it short. 

Let me know if I have missed anything.

**Comment by rolandomunoz** [comment]
The line you mentioned as `Save as 300-dpi PNG file... 'outputFolder$'\waveform_'b'.png` will never run because the variable `draw_num` is equal to 0. This is so, because in line 36,  the function `floor()` returns 0. As a consequence, in line 47, `for b from 1 to draw_num`, the code nested inside the loop will never occurs.
I think this problem is more concerned to scripting?

**Comment by PaulBoersma** [comment]
The second occurrence of `Save as 300-dpi PNG file...` will run. Your file is 1209.54 seconds long, so `divide` will be 20 and `view_width` will be 242. As a result, `save_width` will be 241.40, so you are trying to save a PNG files that is 240.80 inches wide. This issue therefore returns to issue #189, which stated that PNG files could not be wider than 240 inches. In fact, you were told the solution already in the discussion of that issue (make your picture less wide). Please do not report this issue a third time, because we do have to spend time on it, just to discover that you asked the question before.
