### ISSUE TITLE
several compiling/logic issues in ./sys/GraphicsScreen.cpp near setWsWindow

### ISSUE THREAD

**Issue by ac2epsilon** [praat/praat#404]
FIX: replace statement with (im not sure of logic in inches but at least will compile)
                Graphics_setWsWindow (
                        me.get(),
                        isdefined (x1inches) ? 0.0 : 0.0, isdefined (x2inches) ?  x2inches : 7.5,
                        isdefined (y1inches) ? y1inches : 1.0, isdefined (y2inches) ? y2inches : 12.0 
                );
COMMON SOLUTION: never use nested ?:, no ?: twice in a row, nor ?: with parentheses and generelly avoid it at all .) 
EVEN LIL BETTER: overload isdefined() to accept default value. And look: isdefined(double) looks and sounds extremally un.. unhappy. Someone can imagime isDefined(Double) in some TypeScript or Scala, but double is always allocated and so defined. Even takin we use something magic like NAN it will be defined anyway (and can be compared for example)

**Comment by PaulBoersma** [comment]
yeah, forgot to test this change for Linux. Corrected now. Your version was good.
isdefined() and isundef() are modelled on isfinite() and isinf(), hence the perhaps unusual look. The thing corresponds to what is called "undefined" in the user interface or in the script language, that's why we have always used the terms "(un)defined" for this; we did not want a language that distinguishes "NA", "NULL", "NaN" and "Inf" (that's R; hard to tell which of the four occurs when). By the way, "allocated and so defined" refers to syntax, but we needed a semantic definition. For instance, in mathematics one can say that the square root of a negative number is "not defined"; likewise, the value of F0 is "undefined" in voiceless stretches. Those are our uses for this thing; it's mathematical or physical undefinedness rather than a technical computer-undefinedness such as occurs with null pointers.
