### ISSUE TITLE
"Pitch: subtract linear fit" enum values are mismatched by behaviour

### ISSUE THREAD

**Issue by YannickJadoul** [praat/praat#437]
The action for "Pitch: subtract linear fit" allows the selection of different pitch units (cfr. https://github.com/praat/praat/blob/master/fon/praat_Fon.cpp#L1852-L1864).

However, the chosen value returned from the form's enum is then passed on as an integer (so basically untyped), and is mismatched against the actual C++ enum's values (cfr. https://github.com/praat/praat/blob/master/fon/Pitch_enums.h) in `structPitch::v_convertStandardToSpecialUnit` (cfr. https://github.com/praat/praat/blob/master/fon/Pitch.cpp#L97-L119).

Unless I am overlooking something, this looks like something that's not intended?

**Comment by PaulBoersma** [comment]
Well spotted. We recently converted many ints (i.e. untyped enums) to C++11 enums, with automatic generation of option menus, so that these things will be prevented from ever happening again. This one was not converted yet, and it is indeed a bug, leading to semitone fitting when ERB fitting was asked for. We will use a separate enum for these subtraction (or fit) cases (because semitones re 100 Hz is the same as semitones re 440 Hz when it comes to subtractions and fits).

**Comment by PaulBoersma** [comment]
Fixed for the moment by supplying the normal kPitch_unit (with the multiple semitone options, which don't really differ).
