### ISSUE TITLE
Installing praat in Ubuntu

### ISSUE THREAD

**Issue by jesinj** [praat/praat#514]
Hi,

I have been using praat with Windows for long, but need to port to Ubuntu now for project purposes.
I have been trying to install Praat in ubunutu. Been fairly new to the system, the statement in Read.md "If your Unix isn’t Linux, you may have to edit the library names in the makefile (you may need pthread, gtk-x11-2.0, gdk-x11-2.0, atk-1.0, pangoft2-1.0, gdk_pixbuf-2.0, m, pangocairo-1.0, cairo, gio-2.0, pango-1.0, freetype, fontconfig, gobject-2.0, gmodule-2.0, gthread-2.0, rt, glib-2.0)."

Can someone please explain what change is actually required, and where should it be made?

**Comment by chrisbrickhouse** [comment]
Ubuntu runs on the Linux kernel and so that particular caveat doesn't apply. You can install it from the terminal (known as the command line on windows) using the default package manager, apt, using the following command:
```
sudo apt-get install praat
```
Sudo lets this command run with root (administrator) access, so you will need to enter your password. For more info on packages, see the [Guide to Linux for Beginners post about it](http://www.control-escape.com/linux/lx-swinstall.html)

The version in [Ubuntu's Universe repository](https://help.ubuntu.com/community/Repositories/Ubuntu) is from 22 July 2017 and is version 6.0.30 which is not the cutting edge version of Praat (that's 6.0.35) but is not significantly different for most uses. If you run into problems, you can just as easily download the binary from [the Praat website](http://www.fon.hum.uva.nl/praat/download_linux.html) and it should run just by extracting it and double clicking on it. It is better to use the package manager though because it will automatically handle updates, while using the binary requires you to manually check the website for updates.

**Comment by jesinj** [comment]
Hi

Thanks for the reply.

I have already installed praat using the sudo command. It work except there is no audio.

I tried to install praat from source to solve the audio issue.

**Comment by PaulBoersma** [comment]
You are asking what changes you have to make in the makefile. You didn't, however, tell us what happens if you make *no* changes. Perhaps you didn't even try, regarding that you wrote "where should the change be made?" The change (if any, but first try without changes) should be made in the makefile, i.e. in `makefile.defs.linux.pulse` before you copy it to `makefile.defs`, or in `makefile.defs` after you copied it.
