### ISSUE TITLE
Incorrect mode detection while running with prove

### ISSUE THREAD

**Issue by jjatria** [praat/praat#72]
Running Praat from the command line through [`prove`](https://metacpan.org/pod/distribution/Test-Harness/bin/prove) results in Praat incorrectly trying to open the test scripts instead of running them.

`prove` is a Perl-based utility to run [TAP](http://testanything.org/) tests. As such, it makes it possible to use any interpreter through its [`--exec` option](https://metacpan.org/pod/distribution/Test-Harness/bin/prove#exec), and not just Perl itself. However, this does not work in Praat v6.0 at least.

Here's a test case:

    # cpanm Test::Harness or sudo apt-get install libtest-harness-perl
    # but prove should come with the standard Perl distribution
    git clone http://gitlab.com/cpran/plugin_testsimple.git
    cd plugin_testsimple
    prove --exec "praat"

The last command runs the tests (which by default match `./t/*.t`) through `praat`, and should result in the output of each of the scripts being parsed by `prove` for general statistics. Instead, each test script is read and opened in the Praat editor in turn.

The problem is not related to the extensions of the individual test scripts (in this case, `t`). It is probably related to the way in which `prove` calls Praat internally.

I guess this should be fixed by improving the detection of the environment under which Praat is called, but in the meantime it could be fixed by implementing an `--exec` or `--run` option in Praat itself (as once planned) to _force_ execution mode (bypassing the detection altogether).

BTW: This was using Praat 6.0 under Kubuntu 14.04, with Perl 5.22 and TAP::Harness 3.35

**Comment by jjatria** [comment]
@PaulBoersma This means that the automated tests used by CPrAN are currently broken without a repair upstream. If you have time to take a look at this at some point, that'd be great.

**Comment by PaulBoersma** [comment]
did this *ever* work? if so, on what platform?

**Comment by jjatria** [comment]
Oh, this _definitely_ worked. It actualy worked on Windows, Linux, and Mac up to the version before 6.0. This has been a part of CPrAN since last May, and has worked continuously since then.

You can see for yourself if you downgrade Praat to, say, 5.4.22 and try the commands I put up on the example above.

**Comment by PaulBoersma** [comment]
Let me guess -- now it only works on Windows, but not on the Mac or Linux? The first thing that comes to mind would be that isatty returns false in this situation. Do any of the following work?:
prove --exec "praat -"   (unlikely, but just in case prove passes the content of the script in a pipe)
prove --exec "bash praat"

**Comment by PaulBoersma** [comment]
Why isn't there a label for "a change in undocumented behavior" other than "bug"? ;)

**Comment by jjatria** [comment]
Actually, I haven't tried it on Mac or on Windows, I only know that it does not work on Linux (testers welcome!). I tried both your alternative commands:

`prove --exec "praat -"` just holds there, I imagine waiting for input that never comes. A poignant metaphor for life itself.

`prove --exec "bash praat"` complains that it "cannot execute binary file", which is the same error I get if I just try `bash praat`.

> Why isn't there a label for "a change in undocumented behavior" other than "bug"? ;)

The project is young? :)

But more seriously... is this really "undocumented behavior"? I mean, `prove` is supposed to work by passing the test to an interpreter and parsing the stream of results, and `praat` is supposed to execute a script that is passed as an argument (from a terminal) and output to STDOUT. And this is documented. The problem here is that Praat thinks that, when run by `prove`, it should start the GUI, which is not the case (I used that label thinking this was a bug in the tty detection).

I've been trying (unsuccessfully) to figure out how `prove` calls the command passed with `--exec`. The closest I've got is [this](https://github.com/Perl-Toolchain-Gang/Test-Harness/blob/master/lib/TAP/Harness.pm#L544), but it'll require some more spelunking.

**Comment by PaulBoersma** [comment]
>  praat is supposed to execute a script that is passed as an argument (from a terminal) and output to STDOUT. And this is documented.

Sure. But this presupposes that stdout exists, which is not the case if you start Praat without a command-line environment. Anyway, does `--run` work in version 6.0.03?

**Comment by PaulBoersma** [comment]
And the cause why `bash praat` doesn't work might be that the path to praat is not given. `bash ./praat` might work, if the working directory is set.

**Comment by jjatria** [comment]
Yes, `prove --exec "praat --run"` works. Thank you!

(FYI, `prove --exec "bash /full/path/to/praat"` doesn't work either).

This works as a workaround, but I still think this means that the tty detection is more fragile than we'd like. Having to run `praat --run` only for versions >=6.0.03, `praat` for versions <=5.4.22, and not being able to run for versions 6.0 ~ 6.0.02 is far from ideal.

Maybe a way to prevent this would be to have "release candidates", so that before a major version change other users can try things out and point out behaviours that, like this one, get broken. That way major versions could be considered to be more stable. What do you think?

**Comment by jjatria** [comment]
This is tricky. I've been trying to write something so that I can safely detect what version of Praat is running, and I don't think it can be done, at least not from Perl.

For versions >=6.0 we have `--version`, which makes things easier. But `--version` will cause earlier versions (at least 5.4.22) to crash. This can be wrapped in a `try` block, so it shouldn't be that problematic, but Praat crashes _after_ starting the GUI. So not only is it disconcerting for users, but it also makes it impossible to use this programmatically, since Praat requires user input.

Alternatively, we could run a script that said `printline praatVersion`. This will work for all versions of Praat, as long as it is executed. But (at least from Perl) Praat 6.0.03 will open the script for editing instead of running it unless `--run` is used, and this option will cause versions <= 6.0.02 to crash, also requiring user input.

We've backed ourselves into a corner.

I've been trying to find ways to disable the GUI for Praat, to force it to crash if it attempts to open the GUI, but this will likely have to be platform dependent, and I haven't found a way to do it yet. Any ideas are welcome.

**Comment by jjatria** [comment]
Just a short update: the `system` function in Perl does run Praat in such a way that `isatty` accurately detect as a terminal (as long as the output is not captures in any way, this includes `Capture::Tiny` and other such).

The version of Praat can be captured by running a script saying `praatVersion$ > some_file` and then reading the contents of that file. This at least works on all versions from 5.4.22 through 6.0.03.

**Comment by PaulBoersma** [comment]
Distributing beta versions is not a general solution. There will always be bugs that require thousands of downloads and users to be found, and those bugs therefore tend to come out at advertised releases, not before. I spoke before about the foreseeable problem with --version, and spoke before about my doubts about the reliability of command line detection. For the SCITE case, this is actually OK, because `praatcon` just has to be replaced with `praat --run`; as for `prove`, I don't yet know.

And we're not in a corner. Praat is a living program, and almost every version is better than the previous. That 6.0.03 is better in several respects than 6.0, 6.0.01 and 6.0.02 is no coincidence. Whether 6.0.03 is relatively bug-free can only be established by having it around for weeks. As for your version checking, you could just prevent people from using 6.0, 6.0.01 or 6.0.02, if that is indeed the degree of detail with which you create your software (and that I have advised against).

The real solution would have been to go with my original plan and require `--run` in 6.0. In that case, we would not have relied on undocumented behavior of operating systems (does a double-clicked process have a parent? some Windowses say yes, some say no; does isatty always give us what we want? perhaps not). This is something to learn from for me: namely, that it is better to continue with defensive programming, i.e. with things that we know will certainly work (such as `--run`). In the mean time, I will update the manual to say that `--open` opens the file(s) and `--run` runs the file, and that providing neither leads to unguaranteed behavior.

**Comment by PaulBoersma** [comment]
Here is why `isatty` doesn't work for `prove`. I tried to use the `isatty` trick in file redirections and pipes:

   praat myScript.praat > out.txt
   praat myScript.praat | grep hello

In both cases, the GUI is started, because an output file is not a teletype, and a pipe is not a teletype. The only way to run the script is

   praat --run myScript.praat > out.txt
   praat --run myScript.praat | grep hello

These Unix tricks at least run correctly on the Mac and Linux. Apparently, `prove` has its helper programs output to a file or pipe, that's all.

So, how can we make command line detection more reliable, if not with `isatty`?

**Comment by PaulBoersma** [comment]
With getppid() one can get the process id of the parent process, and with "ps -p *parent-process-id* -o comm" one can then get its name. Double-clicking Praat yields as a parent process "launchd" on the Mac, and "init --user" on Linux. Otherwise, the parent is something like "bash", "tcsh", or an external program that calls a system()-like procedure. This seems to be a better heuristic than using `isatty`, but I would still not call it robust.

**Comment by jjatria** [comment]
> Distributing beta versions is not a general solution. There will always be bugs that require thousands of downloads and users to be found, and those bugs therefore tend to come out at advertised releases, not before.

For sure. It is normal to see _hotfixes_ being released soon after a major version change because a larger user base will encounter a lot more bugs and border conditions. But a beta release takes care of the most egregious ones (like the problems with `isatty` that we've encountered). This is why the beta model is so widely used. Not because it catches _all_ the bugs (how could it), but because it takes care of most of the big nasty ones.

> The real solution would have been to go with my original plan and require --run in 6.0.

Maybe. Or maybe there is a better solution that we've still haven't thought of. I completely agree on your stance for "defensive programming", but I'd say part of that defensive programming is to roll out changes --- particularly large changes --- slowly and after significant testing in the broadest conditions possible. And in this case, I at least only heard about the proposed API changes three days before it was released, which didn't leave a lot of time for testing by people other than yourself.

> This seems to be a better heuristic than using isatty, but I would still not call it robust.

Sounds good. So the idea would be to start the GUI if the parent ID is one of the known GUI ones? I guess that's better than the other way around, since any number of processes might start Praat from the terminal, but there are much fewer desktop environments out there. Or what are you thinking about?

**Comment by PaulBoersma** [comment]
Can the problems with `isatty` be called "egregious"? Its use in Praat now seems to guarantee that double-clicking starts the GUI and that typing the `praat` command into a CLI or Python runs the script file, so I simply think we will keep it in for the time being. The problems entail no more than that in some situations one had better follow the advice to use `--run` explicitly, which simply means that the programmer makes explicit what they want rather than have Praat guess.

But actually, yes, we took a different approach this time than usually. Usually, we would make changes to Praat until one month before an advertised release, and in that month only remove any bugs that would be reported (or that we would find), and then do nothing at all in the last week. This time it was different because a discrete API incompatibility had to be announced. With hindsight, we could perhaps have put the `--run` advice in the manual much earlier.

> start the GUI if the parent ID is one of the known GUI ones? I guess that's better than the other way around

I disagree, because this preference only goes for programmers, not for normal users. Thinking of those 6000 downloaders, I would say that overseeing one method of starting the GUI (which leads to the non-GUI version dropping its complaints into a black hole) is worse than overseeing one method of starting a CLI (which leads to the GUI-version popping up and which can be repaired with `--run`).

**Comment by jjatria** [comment]
> Can the problems with isatty be called "egregious"?

I meant that in the sense that it was an error that was easy to come across. A conspicuous problem. Redirecting the output of programs in the terminal is a fundamental part of the workflow. But I didn't mean anything else by it.

**Comment by PaulBoersma** [comment]
OK, we now all understand the issue in the same way :)
